name: Kwiki-FetchRSS
version: 0.08
abstract: WAFL Plugin To Fetch an RSS Feed
license: perl
distribution_type: module
requires:
  Cache::FileCache: 0
  LWP::UserAgent: 0
  XML::Feed: 0
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
